DRAC-153 | added accounts module
menklab/dracarys-backend pull request #20
Opened 2023-01-04 04:03 UTC by stasmenklab

Added accounts module

2023-01-04 10:02 UTC, Zhuravlev1 requested changes

2023-01-04 10:02 UTC, Zhuravlev1 commented on src/common/errors/errors.ts
> +      message: 'not authorized'
pls, use a prettier config from the root of project. And before pushing be sure that prettier(npm run format) was run.

2023-01-04 10:02 UTC, Zhuravlev1 commented on src/modules/account/dtos/account.dto.ts
> +  created_at: Date
Pls, use cameCase format for naming variables and properties

2023-01-04 10:02 UTC, Zhuravlev1 commented on src/modules/account/account.service.ts
> +  public async getAll(program_id: number): Promise<Account[]> {
let's change response type from **Account[]** to **AccountDto[]**
it's not a controller responsibility to build a response. So, in the service we should manipulate with object like toEntity, toDto etc.

2023-01-04 10:02 UTC, Zhuravlev1 commented on src/modules/account/account.service.ts
> +    toUpdateAccountEntity(account, data)
why didn't you explicitly change the object?

2023-01-04 10:02 UTC, Zhuravlev1 commented on src/modules/account/dtos/create-account/create-account.dto.ts
> +  program_id: number
pls, follow cameCase rule

2023-01-04 10:02 UTC, Zhuravlev1 commented on src/modules/account/mappers/account.mapper.ts
> +export function toAccountsDto(accounts: Account[]): AccountDto[] {
let's create a class
```
export class AccountMapper {
 static toDto()
 static toCreateEntity()
 static toUpdateEntity()
 }
```

Also, don't need a method toAccount**s** , call **accounts.map()** in the service  level

2023-01-04 10:02 UTC, Zhuravlev1 commented on src/modules/account/mappers/account.mapper.ts
> +  account.name = data.name
use Object.assign

2023-01-04 10:02 UTC, Zhuravlev1 commented on src/modules/app/app.module.ts
> +            httpOnly: false
do we need maxAge property?

2023-01-04 10:02 UTC, Zhuravlev1 commented on src/orm/entities/account.entity.ts
>  export class Account extends BaseEntity {
Account -> AccountEntity

2023-01-04 10:02 UTC, Zhuravlev1 commented on src/orm/entities/base.entity.ts
> +  created_at: Date
revert pls

2023-01-04 10:02 UTC, Zhuravlev1 commented on src/modules/account/account.controller.ts
> +    return toAccountDto(account)
build a response (toDto) - it's the responsibility of service

2023-01-04 21:10 UTC, drewcouturier commented on src/common/errors/errors.ts
> +      message: 'not authorized'
@Zhuravlev1 I can add a check for all pull requests that requires the changes to match the prettier config. Then you wouldn't have to spend time requesting formatting changes. Let me know if that would be helpful

2023-01-05 07:18 UTC, Zhuravlev1 approved these changes

2023-01-05 07:18 UTC, merged