DRAC-360 | fixed instructions details reversed order
menklab/dracarys-backend pull request #60
Opened 2023-02-16 05:19 UTC by stasmenklab

2023-02-16 09:55 UTC, Zhuravlev1 requested changes

2023-02-16 09:55 UTC, Zhuravlev1 commented on src/modules/instruction/instruction.service.ts
> +    if(!programId){
How is it possible? programId is not optional

2023-02-16 09:55 UTC, Zhuravlev1 commented on src/modules/instruction/instruction.service.ts
> +      const structure = this.generateStructure(instruction.elements.reverse(), camelCaseName)
it's better to reverse it on the DB level

2023-02-17 16:06 UTC, stasmenklab commented on src/modules/instruction/instruction.service.ts
> +    if(!programId){
If I don't pass in the programId in as the query param in the url while making request, I can log in here as undefined

2023-02-17 16:11 UTC, Zhuravlev1 commented on src/modules/instruction/instruction.service.ts
> +    if(!programId){
but you can check it by JOI in the controller level, is not?

2023-02-17 19:05 UTC, Zhuravlev1 approved these changes

2023-02-17 19:05 UTC, merged